package com.example.util

import androidx.compose.runtime.staticCompositionLocalOf

data class AppStrings(
    // App info
    val appName: String,
    val appDescription: String,
    val developerName: String,
    val developerContact: String,
    val developerInfoTitle: String,
    val versionLabel: String,
    val developerLabel: String,
    val contactLabel: String,
    val descriptionLabel: String,

    // Navigation
    val navVideos: String,
    val navFolders: String,
    val navPlaylists: String,
    val navSettings: String,

    // Videos Screen
    val searchVideosPlaceholder: String,
    val sortVideos: String,
    val toggleView: String,
    val folderPrefix: String,
    val noVideosFound: String,
    val noVideosFoundDesc: String,
    val noMatchingVideos: String,
    val noMatchingVideosDesc: String,
    val videoCountSingle: String,
    val videoCountPlural: String,
    val refreshVideos: String,

    // Video Options Menu
    val playVideo: String,
    val addToPlaylist: String,
    val videoDetails: String,

    // Folders Screen
    val videoFoldersTitle: String,
    val foldersFoundCount: String,
    val noFoldersFound: String,

    // Playlists Screen
    val playlistsTitle: String,
    val createPlaylist: String,
    val newPlaylistTitle: String,
    val playlistNamePrompt: String,
    val playlistNameHint: String,
    val playlistNameEmptyError: String,
    val noPlaylistsYet: String,
    val noPlaylistsYetDesc: String,
    val playAll: String,
    val deletePlaylist: String,
    val deletePlaylistItem: String,
    val customPlaylistSubtitle: String,
    val emptyPlaylistDesc: String,

    // Dialogs & Actions
    val create: String,
    val cancel: String,
    val ok: String,
    val close: String,
    val clear: String,
    val delete: String,
    val removeSubtitle: String,

    // Video Details Dialog
    val detailsTitle: String,
    val fileNameLabel: String,
    val folderLabel: String,
    val durationLabel: String,
    val fileSizeLabel: String,
    val resolutionLabel: String,
    val mimeTypeLabel: String,

    // Sort Dialog
    val sortDialogTitle: String,
    val sortNewest: String,
    val sortOldest: String,
    val sortNameAsc: String,
    val sortNameDesc: String,
    val sortSizeLargest: String,
    val sortSizeSmallest: String,

    // Player Screen
    val resumedFrom: String,
    val subtitles: String,
    val playbackSpeed: String,
    val aspectRatio: String,
    val rotateScreen: String,
    val lockScreen: String,
    val unlockScreen: String,
    val screenLockedNotice: String,
    val aspectRatioFit: String,
    val aspectRatioFill: String,
    val aspectRatio16_9: String,
    val aspectRatio4_3: String,
    val speedNormal: String,
    val subtitleFilePrompt: String,
    val playerErrorDecoderReclaimed: String,
    val playerErrorGeneral: String,
    val retry: String,
    val goBack: String,
    val volumeLabel: String,
    val brightnessLabel: String,

    // Settings Screen Headers
    val settingsTitle: String,
    val sectionPlayback: String,
    val sectionLibrary: String,
    val sectionSubtitles: String,
    val sectionStorage: String,
    val sectionLanguage: String,
    val sectionAbout: String,

    // Settings: Playback
    val resumePlaybackTitle: String,
    val resumePlaybackSubtitle: String,
    val clearHistoryTitle: String,
    val clearHistorySubtitle: String,
    val clearHistoryDialogTitle: String,
    val clearHistoryDialogDesc: String,
    val defaultSpeedTitle: String,
    val defaultSpeedSubtitle: String,
    val autoLockTitle: String,
    val autoLockSubtitle: String,
    val autoLockTimeoutTitle: String,
    val secondsUnit: String,

    // Settings: Library
    val sortOrderTitle: String,
    val sortOrderSubtitle: String,
    val hideShortVideosTitle: String,
    val hideShortVideosSubtitle: String,
    val shortDurationThresholdTitle: String,

    // Settings: Subtitle Appearance
    val subtitleFontSizeTitle: String,
    val subtitleColorTitle: String,
    val subtitleBackgroundTitle: String,
    val subtitleBackgroundSubtitle: String,
    val subtitlePreviewSample: String,
    val fontSmall: String,
    val fontMedium: String,
    val fontLarge: String,
    val fontExtra: String,
    val colorWhite: String,
    val colorYellow: String,
    val colorCyan: String,
    val colorGreen: String,

    // Settings: Storage
    val storageUsageTitle: String,
    val storageFree: String,
    val storageUsed: String,
    val storageTotalVideosSizeTitle: String,
    val storageQueriedSuccess: String,

    // Settings: Language
    val appLanguageTitle: String,
    val appLanguageSubtitle: String,
    val langEnglish: String,
    val langArabic: String,
    val langChangedToast: String,

    // Permissions
    val grantPermission: String,
    val grantStorageAccess: String,
    val storageAccessRequired: String,
    val permissionRationale: String,
    val restart: String
) {
    companion object {
        val English = AppStrings(
            appName = "Vidoo",
            appDescription = "100% offline local video player",
            developerName = "Ahmad Asaad",
            developerContact = "01271203502",
            developerInfoTitle = "Developer Information",
            versionLabel = "Version",
            developerLabel = "Developer",
            contactLabel = "Contact number",
            descriptionLabel = "About Vidoo",

            navVideos = "Videos",
            navFolders = "Folders",
            navPlaylists = "Playlists",
            navSettings = "Settings",

            searchVideosPlaceholder = "Search videos…",
            sortVideos = "Sort videos",
            toggleView = "Toggle view",
            folderPrefix = "Folder",
            noVideosFound = "No videos found",
            noVideosFoundDesc = "Add video files to your device storage to view them here.",
            noMatchingVideos = "No matching videos found",
            noMatchingVideosDesc = "Try searching with a different term",
            videoCountSingle = "video",
            videoCountPlural = "videos",
            refreshVideos = "Refresh Videos",

            playVideo = "Play Video",
            addToPlaylist = "Add to Playlist",
            videoDetails = "Video Details",

            videoFoldersTitle = "Video Folders",
            foldersFoundCount = "folders found",
            noFoldersFound = "No folders with videos found",

            playlistsTitle = "Playlists",
            createPlaylist = "Create Playlist",
            newPlaylistTitle = "New Playlist",
            playlistNamePrompt = "Enter a name for your custom playlist:",
            playlistNameHint = "e.g., Favorites, Watch Later",
            playlistNameEmptyError = "Playlist name cannot be empty",
            noPlaylistsYet = "No custom playlists yet",
            noPlaylistsYetDesc = "Create playlists to group and play your favorite videos in sequence.",
            playAll = "Play All",
            deletePlaylist = "Delete Playlist",
            deletePlaylistItem = "Delete Item",
            customPlaylistSubtitle = "Custom playlist",
            emptyPlaylistDesc = "No videos added to this playlist yet.",

            create = "Create",
            cancel = "Cancel",
            ok = "OK",
            close = "Close",
            clear = "Clear",
            delete = "Delete",
            removeSubtitle = "Remove Subtitle",

            detailsTitle = "Video Details",
            fileNameLabel = "File Name",
            folderLabel = "Folder",
            durationLabel = "Duration",
            fileSizeLabel = "File Size",
            resolutionLabel = "Resolution",
            mimeTypeLabel = "MIME Type",

            sortDialogTitle = "Sort Videos",
            sortNewest = "Newest first",
            sortOldest = "Oldest first",
            sortNameAsc = "Name (A–Z)",
            sortNameDesc = "Name (Z–A)",
            sortSizeLargest = "Size (Largest)",
            sortSizeSmallest = "Size (Smallest)",

            resumedFrom = "Resumed from",
            subtitles = "Subtitles",
            playbackSpeed = "Playback Speed",
            aspectRatio = "Aspect Ratio",
            rotateScreen = "Rotate Screen",
            lockScreen = "Lock Screen",
            unlockScreen = "Unlock Screen",
            screenLockedNotice = "Screen locked. Tap unlock icon to restore controls.",
            aspectRatioFit = "Fit to Screen",
            aspectRatioFill = "Fill Screen (Crop)",
            aspectRatio16_9 = "16:9 Aspect",
            aspectRatio4_3 = "4:3 Aspect",
            speedNormal = "Normal",
            subtitleFilePrompt = "Active Subtitle",
            playerErrorDecoderReclaimed = "Video decoder was reclaimed by the system. Tap Retry to reload.",
            playerErrorGeneral = "Unable to play video",
            retry = "Retry",
            goBack = "Go Back",
            volumeLabel = "Volume",
            brightnessLabel = "Brightness",

            settingsTitle = "Settings",
            sectionPlayback = "Playback",
            sectionLibrary = "Library",
            sectionSubtitles = "Subtitle Appearance",
            sectionStorage = "Storage",
            sectionLanguage = "Language",
            sectionAbout = "About",

            resumePlaybackTitle = "Resume playback",
            resumePlaybackSubtitle = "Remember and restore last watched position",
            clearHistoryTitle = "Clear playback history",
            clearHistorySubtitle = "Reset saved progress for all videos",
            clearHistoryDialogTitle = "Clear History",
            clearHistoryDialogDesc = "This will remove all resume timestamps and playback records. Are you sure?",
            defaultSpeedTitle = "Default playback speed",
            defaultSpeedSubtitle = "Speed applied automatically when opening a video",
            autoLockTitle = "Auto-lock screen during playback",
            autoLockSubtitle = "Automatically lock player controls after inactivity",
            autoLockTimeoutTitle = "Auto-lock timeout",
            secondsUnit = "s",

            sortOrderTitle = "Sort order",
            sortOrderSubtitle = "Default order for videos in library",
            hideShortVideosTitle = "Hide short videos",
            hideShortVideosSubtitle = "Exclude brief clips below duration threshold from library",
            shortDurationThresholdTitle = "Duration threshold",

            subtitleFontSizeTitle = "Font size",
            subtitleColorTitle = "Text color",
            subtitleBackgroundTitle = "Semi-transparent background",
            subtitleBackgroundSubtitle = "Show subtle dark backdrop behind subtitles for readability",
            subtitlePreviewSample = "Sample subtitle preview text (00:01:24)",
            fontSmall = "Small",
            fontMedium = "Medium",
            fontLarge = "Large",
            fontExtra = "Extra",
            colorWhite = "White",
            colorYellow = "Yellow",
            colorCyan = "Cyan",
            colorGreen = "Green",

            storageUsageTitle = "Storage used / available",
            storageFree = "Free",
            storageUsed = "Used",
            storageTotalVideosSizeTitle = "Total videos size detected",
            storageQueriedSuccess = "Internal storage analyzed",

            appLanguageTitle = "App language",
            appLanguageSubtitle = "Select preferred display language for the application",
            langEnglish = "English",
            langArabic = "العربية (Arabic)",
            langChangedToast = "Language set to English",

            grantPermission = "Grant Permission",
            grantStorageAccess = "Grant Storage Access",
            storageAccessRequired = "Storage Access Required",
            permissionRationale = "Vidoo scans your device storage to list, organize, and play your local videos without sending any data online.",
            restart = "Restart"
        )

        val Arabic = AppStrings(
            appName = "Vidoo",
            appDescription = "مشغل فيديو محلي بدون إنترنت 100%",
            developerName = "Ahmad Asaad",
            developerContact = "01271203502",
            developerInfoTitle = "معلومات المطور",
            versionLabel = "الإصدار",
            developerLabel = "المطور",
            contactLabel = "رقم التواصل",
            descriptionLabel = "عن تطبيق Vidoo",

            navVideos = "الفيديوهات",
            navFolders = "المجلدات",
            navPlaylists = "قوائم التشغيل",
            navSettings = "الإعدادات",

            searchVideosPlaceholder = "البحث في الفيديوهات…",
            sortVideos = "ترتيب الفيديوهات",
            toggleView = "تبديل طريقة العرض",
            folderPrefix = "مجلد",
            noVideosFound = "لم يتم العثور على فيديوهات",
            noVideosFoundDesc = "أضف ملفات الفيديو إلى مساحة تخزين جهازك لعرضها هنا.",
            noMatchingVideos = "لا توجد فيديوهات مطابقة للبحث",
            noMatchingVideosDesc = "جرّب البحث بكلمة أخرى",
            videoCountSingle = "فيديو",
            videoCountPlural = "فيديوهات",
            refreshVideos = "تحديث الفيديوهات",

            playVideo = "تشغيل الفيديو",
            addToPlaylist = "إضافة إلى قائمة تشغيل",
            videoDetails = "تفاصيل الفيديو",

            videoFoldersTitle = "مجلدات الفيديو",
            foldersFoundCount = "مجلدات تم العثور عليها",
            noFoldersFound = "لم يتم العثور على مجلدات بها فيديوهات",

            playlistsTitle = "قوائم التشغيل",
            createPlaylist = "إنشاء قائمة تشغيل",
            newPlaylistTitle = "قائمة تشغيل جديدة",
            playlistNamePrompt = "أدخل اسماً لقائمة التشغيل الخاصة بك:",
            playlistNameHint = "مثال: المفضلة، المشاهدة لاحقاً",
            playlistNameEmptyError = "لا يمكن أن يكون اسم القائمة فارغاً",
            noPlaylistsYet = "لا توجد قوائم تشغيل مخصصة حتى الآن",
            noPlaylistsYetDesc = "أنشئ قوائم تشغيل لتجميع وتشغيل مقاطع الفيديو المفضلة لديك بالتتابع.",
            playAll = "تشغيل الكل",
            deletePlaylist = "حذف القائمة",
            deletePlaylistItem = "حذف العنصر",
            customPlaylistSubtitle = "قائمة مخصصة",
            emptyPlaylistDesc = "لم تتم إضافة أي فيديوهات لهذه القائمة بعد.",

            create = "إنشاء",
            cancel = "إلغاء",
            ok = "حسناً",
            close = "إغلاق",
            clear = "مسح",
            delete = "حذف",
            removeSubtitle = "إزالة الترجمة",

            detailsTitle = "تفاصيل الفيديو",
            fileNameLabel = "اسم الملف",
            folderLabel = "المجلد",
            durationLabel = "المدة",
            fileSizeLabel = "حجم الملف",
            resolutionLabel = "الدقة",
            mimeTypeLabel = "نوع الملف",

            sortDialogTitle = "ترتيب الفيديوهات",
            sortNewest = "الأحدث أولاً",
            sortOldest = "الأقدم أولاً",
            sortNameAsc = "الاسم (أ–ي)",
            sortNameDesc = "الاسم (ي–أ)",
            sortSizeLargest = "الحجم (الأكبر)",
            sortSizeSmallest = "الحجم (الأصغر)",

            resumedFrom = "تم الاستئناف من",
            subtitles = "الترجمة",
            playbackSpeed = "سرعة التشغيل",
            aspectRatio = "نسبة العرض",
            rotateScreen = "تدوير الشاشة",
            lockScreen = "قفل الشاشة",
            unlockScreen = "إلغاء قفل الشاشة",
            screenLockedNotice = "الشاشة مقفلة. انقر على أيقونة القفل لاستعادة عناصر التحكم.",
            aspectRatioFit = "ملاءمة الشاشة",
            aspectRatioFill = "ملء الشاشة (اقتصاص)",
            aspectRatio16_9 = "نسبة 16:9",
            aspectRatio4_3 = "نسبة 4:3",
            speedNormal = "عادي",
            subtitleFilePrompt = "ملف الترجمة النشط",
            playerErrorDecoderReclaimed = "استعاد النظام موارد المشغل. اضغط إعادة المحاولة للتشغيل.",
            playerErrorGeneral = "تعذر تشغيل الفيديو",
            retry = "إعادة المحاولة",
            goBack = "رجوع",
            volumeLabel = "الصوت",
            brightnessLabel = "السطوع",

            settingsTitle = "الإعدادات",
            sectionPlayback = "التشغيل",
            sectionLibrary = "المكتبة",
            sectionSubtitles = "مظهر الترجمة",
            sectionStorage = "مساحة التخزين",
            sectionLanguage = "اللغة",
            sectionAbout = "حول التطبيق",

            resumePlaybackTitle = "استئناف التشغيل",
            resumePlaybackSubtitle = "تذكر واستعادة موضع آخر مشاهدة لكل فيديو",
            clearHistoryTitle = "مسح سجل التشغيل",
            clearHistorySubtitle = "إعادة ضبط التقدم المحفوظ لجميع مقاطع الفيديو",
            clearHistoryDialogTitle = "تأكيد مسح السجل",
            clearHistoryDialogDesc = "سيؤدي هذا إلى إزالة جميع نقاط الاستئناف المحفوظة. هل أنت متأكد؟",
            defaultSpeedTitle = "سرعة التشغيل الافتراضية",
            defaultSpeedSubtitle = "السرعة المطبقة تلقائياً عند فتح أي فيديو",
            autoLockTitle = "القفل التلقائي للشاشة أثناء التشغيل",
            autoLockSubtitle = "قفل عناصر التحكم تلقائياً بعد فترة من عدم اللمس",
            autoLockTimeoutTitle = "مدة القفل التلقائي",
            secondsUnit = "ث",

            sortOrderTitle = "ترتيب الفيديوهات",
            sortOrderSubtitle = "الترتيب الافتراضي للفيديوهات في المكتبة",
            hideShortVideosTitle = "إخفاء الفيديوهات القصيرة",
            hideShortVideosSubtitle = "استبعاد المقاطع الأقصر من المدة المحددة من المكتبة",
            shortDurationThresholdTitle = "الحد الأدنى للمدة",

            subtitleFontSizeTitle = "حجم الخط",
            subtitleColorTitle = "لون النص",
            subtitleBackgroundTitle = "خلفية شبه شفافة",
            subtitleBackgroundSubtitle = "إظهار خلفية داكنة خفيفة خلف نصوص الترجمة لسهولة القراءة",
            subtitlePreviewSample = "نموذج معاينة نص الترجمة (00:01:24)",
            fontSmall = "صغير",
            fontMedium = "متوسط",
            fontLarge = "كبير",
            fontExtra = "كبير جداً",
            colorWhite = "أبيض",
            colorYellow = "أصفر",
            colorCyan = "سماوي",
            colorGreen = "أخضر",

            storageUsageTitle = "المساحة المستخدمة / المتاحة",
            storageFree = "المتبقي",
            storageUsed = "المستخدم",
            storageTotalVideosSizeTitle = "إجمالي مساحة الفيديوهات المكتشفة",
            storageQueriedSuccess = "تم تحليل وحدة التخزين الداخلية بنجاح",

            appLanguageTitle = "لغة التطبيق",
            appLanguageSubtitle = "اختر لغة العرض المفضلة لواجهة التطبيق",
            langEnglish = "English",
            langArabic = "العربية (Arabic)",
            langChangedToast = "تم تفعيل اللغة العربية",

            grantPermission = "منح الإذن",
            grantStorageAccess = "منح إذن الوصول للتخزين",
            storageAccessRequired = "مطلوب إذن الوصول إلى مساحة التخزين",
            permissionRationale = "يقوم Vidoo بفحص مساحة تخزين جهازك لعرض وتنظيم وتشغيل فيديوهاتك المحلية دون إرسال أي بيانات عبر الإنترنت.",
            restart = "إعادة البدء"
        )
    }
}

val LocalAppStrings = staticCompositionLocalOf { AppStrings.English }
